### ISSUE TITLE
Upgrade electron version

### ISSUE THREAD

**Issue by nocon140** [bapatel1/Electron-Angular4-Pouchdb#1]
Unable to upgrade electron 
- Tried using the command "**npm update electron-prebuilt -g**"

**Comment by itsmebhavin** [comment]
@nocon140 Please post some more information like what error message you are having and operating system and all. We have replicated this in our Virtual machine and works fine. Please refer alternative ways to get electron-prebuilt to see if that works,

**Comment by nocon140** [comment]
Thank you .. 
I followed the instructions given in the [link](https://stackoverflow.com/questions/32311095/i-cant-update-electron-with-npm) and was able to achieve it.
