### ISSUE TITLE
Packaging Electron to win32 x64

### ISSUE THREAD

**Issue by GeorgeWrightz** [bapatel1/Electron-Angular4-Pouchdb#2]
Hi , 

Good work on the Electron-ng4-PouchDB !!

However I am looking to package this app for a windows platform. Tried using electron-packager and after the packaging, when clicked on the .exe file - got the error " cannot find module electron-window-state ".

Used basic commands with electron-packager
Is there something I am missing ?

Using : Node - 6.11.0, electron - 1.6.11 , OS - Windows 10

**Comment by itsmebhavin** [comment]
Thanks @GeorgeWrightz , appreciate your feedback on this product. Also, we have sort of done packaging and all using Gulp in different project so we could do that but i would like to find better solution with this product, just not getting chance yet. If you find any good working solution to package, please let me know. We are using Electron Release Server for release process, just FYI. 

Thanks,

**Comment by itsmebhavin** [comment]
Hi Bhavin, 

Full confession : We here are trying to keep up with technologies ( been a java developer for a decade ), so my friends and I decided to learn Rxjs, Ng4, electron etc and take up a project and start contributing. We are yet to start with build tools like Gulp, Grunt or webpack. Your project was my selection on the board. The only thing lacking is a packager. I tried my bit with electron-packager. 

If you can help me or point me to the right direction on packaging the app. I can convince my friends to take up the project.

All I need is a push !!

In my opinion the pouchDB is a very nice solution. A very niche technology, which I would love to take up and learn. Another reason why I love the technology stack that you have chosen.

Its good see such projects (such as yours) that can help us understand the kind of technology and keep the pushing the boundaries. 

Thanks you for your understanding..

- George

**Comment by itsmebhavin** [comment]
@GeorgeWrightz  I appreciate your interest in this product and trust me, We did similar projects here in my team and we used electron packager with other build tools and packaged it using gulp. So it's do-able and possible for 100%, it just with all other deadline projects at work , I am not getting much time to work on implementing packager right now. My plan is definitely add it within a week or two though. (if you can wait) 

Hope this helps.

**Comment by GeorgeWrightz** [comment]
Great.. good to hear !! 
Will wait for the packager as mentioned , meanwhile will look into other stuff in help section.

Looking forward to work together in this repo...

- George

**Comment by itsmebhavin** [comment]
@GeorgeWrightz  I have created very basic running packaging application sample at `https://github.com/bapatel1/electron-angular4-packaging`. Please try that out. It's using `electron-builder` to build the new installer and update installer. I have used `electron-packager` in past for other projects in production but process involves little manual so i wanted to find out alternatives and this seems to work fine as of now. I will see if i can automate and still use `electron-packager` with all dependencies. 

This sample has same dependencies like electron-window-state etc. and seems to package everything fine. Hope this sample will help you.

**Comment by GeorgeWrightz** [comment]
@bapatel1  Thank you for the sample.

**Comment by itsmebhavin** [comment]
@GeorgeWrightz  let me know if any issue in that sample and also, we will look into `electron-packager` too down the road to see if that works the same way as this sample is working (using `electron-builder`).

**Comment by GeorgeWrightz** [comment]
@bapatel1 
I tried using your packager "https://github.com/bapatel1/electron-angular4-packaging". However if we add "pouchdb": "^6.3.4" in dependencies we get the error due to leveldown@ 1.5.0. 

Note : I am using windows 10 and node 6.11.0

**Comment by itsmebhavin** [comment]
@GeorgeWrightz Please post full error or it's screenshot.

**Comment by GeorgeWrightz** [comment]
Here you go ..


> leveldown@1.5.0 install F:\Workspace\Electron\Test\New folder\electron-angular4-packaging-master\node_modules\leveldown
> prebuild --install

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MSB6006: "CL.exe" exited with code -1073741515. [F:\Workspace\Electron\Test\New folder\electron-angular4-packaging-master\node_modules\leveldown\deps\leveldb\leveldb.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MSB6006: "CL.exe" exited with code -1073741515. [F:\Workspace\Electron\Test\New folder\electron-angular4-packaging-master\node_modules\leveldown\deps\snappy\snappy.vcxproj]

Error output:
prebuild ERR! build error
prebuild ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
prebuild ERR! stack     at ChildProcess.onExit (F:\Workspace\Electron\Test\New folder\electron-angular4-packaging-master\node_modules\node-gyp\lib\build.js:258:23)
prebuild ERR! stack     at emitTwo (events.js:106:13)
prebuild ERR! stack     at ChildProcess.emit (events.js:191:7)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
prebuild ERR! not ok
prebuild ERR! build Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
prebuild ERR! build     at ChildProcess.onExit (F:\Workspace\Electron\Test\New folder\electron-angular4-packaging-master\node_modules\node-gyp\lib\build.js:258:23)
prebuild ERR! build     at emitTwo (events.js:106:13)
prebuild ERR! build     at ChildProcess.emit (events.js:191:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "leveldown@1.5.0"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! leveldown@1.5.0 install: `prebuild --install`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the leveldown@1.5.0 install script 'prebuild --install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs leveldown
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\Workspace\Electron\Test\New folder\electron-angular4-packaging-master\npm-debug.log

    at ChildProcess.childProcess.once.code (F:\Workspace\Electron\Test\New folder\electron-angular4-packaging-master\node_modules\electron-builder-util\src\util.ts:179:14)
    at ChildProcess.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
From previous event:
    at spawn (F:\Workspace\Electron\Test\New folder\electron-angular4-packaging-master\node_modules\electron-builder-util\src\util.ts:142:3)
    at F:\Workspace\Electron\Test\New folder\electron-angular4-packaging-master\node_modules\electron-builder\src\util\yarn.ts:172:5
From previous event:
    at rebuild (F:\Workspace\Electron\Test\New folder\electron-angular4-packaging-master\node_modules\electron-builder\out\util\yarn.js:96:22)
    at F:\Workspace\Electron\Test\New folder\electron-angular4-packaging-master\node_modules\electron-builder\src\util\yarn.ts:21:11
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at installOrRebuild (F:\Workspace\Electron\Test\New folder\electron-angular4-packaging-master\node_modules\electron-builder\out\util\yarn.js:34:21)
    at F:\Workspace\Electron\Test\New folder\electron-angular4-packaging-master\node_modules\electron-builder\src\packager.ts:331:7
    at next (native)
From previous event:
    at Packager.installAppDependencies (F:\Workspace\Electron\Test\New folder\electron-angular4-packaging-master\node_modules\electron-builder\out\packager.js:404:11)
    at F:\Workspace\Electron\Test\New folder\electron-angular4-packaging-master\node_modules\electron-builder\src\packager.ts:227:20
    at next (native)
From previous event:
    at Packager.doBuild (F:\Workspace\Electron\Test\New folder\electron-angular4-packaging-master\node_modules\electron-builder\out\packager.js:340:11)
    at F:\Workspace\Electron\Test\New folder\electron-angular4-packaging-master\node_modules\electron-builder\src\packager.ts:184:52
    at next (native)
From previous event:
    at Packager.build (F:\Workspace\Electron\Test\New folder\electron-angular4-packaging-master\node_modules\electron-builder\out\packager.js:259:11)
    at F:\Workspace\Electron\Test\New folder\electron-angular4-packaging-master\node_modules\electron-builder\src\builder.ts:266:40
    at next (native)
From previous event:
    at build (F:\Workspace\Electron\Test\New folder\electron-angular4-packaging-master\node_modules\electron-builder\out\builder.js:69:21)
    at loadEnv.then (F:\Workspace\Electron\Test\New folder\electron-angular4-packaging-master\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Object.args [as handler] (F:\Workspace\Electron\Test\New folder\electron-angular4-packaging-master\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at Object.self.runCommand (F:\Workspace\Electron\Test\New folder\electron-angular4-packaging-master\node_modules\electron-builder\node_modules\yargs\lib\command.js:233:22)
    at Object.Yargs.self._parseArgs (F:\Workspace\Electron\Test\New folder\electron-angular4-packaging-master\node_modules\electron-builder\node_modules\yargs\yargs.js:1018:24)
    at Object.get [as argv] (F:\Workspace\Electron\Test\New folder\electron-angular4-packaging-master\node_modules\electron-builder\node_modules\yargs\yargs.js:927:19)
    at Object.<anonymous> (F:\Workspace\Electron\Test\New folder\electron-angular4-packaging-master\node_modules\electron-builder\src\cli\cli.ts:43:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dist"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ngelectron@0.0.1 dist: `electron-builder --win --x64 --ia32`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the ngelectron@0.0.1 dist script 'electron-builder --win --x64 --ia32'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ngelectron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-builder --win --x64 --ia32
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ngelectron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ngelectron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\Workspace\Electron\Test\New folder\electron-angular4-packaging-master\npm-debug.log

**Comment by itsmebhavin** [comment]
This means your machine have msbuild isssue. try re-installing node-gyp  and you need to do that from a Command Prompt with Administrator privileges. Right click on cmd and do "run as administrator" and try again.

**Comment by GeorgeWrightz** [comment]
I did update node-gyp and "run as administrator" . I still have the same error as above. 
Also, after updating node-gyp I tried installing leveldown@1.5.0 in a empty folder. I was able to install without any errors ..
 Installed as verbose, the log below for reference : 


prebuild info begin Prebuild version 4.5.0
prebuild info looking for local prebuild @ prebuilds\leveldown-v1.5.0-node-v48-win32-x64.tar.gz
prebuild info looking for cached prebuild @ C:\Users\george\AppData\Roaming\npm-cache\_prebuilds\https-github.com-level-leveldown-releases-download-v1.5.0-leveldown-v1.5.0-node-v48-win32-x64.tar.gz
prebuild info found cached prebuild
prebuild info unpacking @ C:\Users\george\AppData\Roaming\npm-cache\_prebuilds\https-github.com-level-leveldown-releases-download-v1.5.0-leveldown-v1.5.0-node-v48-win32-x64.tar.gz
prebuild info unpack resolved to F:\Workspace\Electron\Test\test2\node_modules\leveldown\build\Release\leveldown.node
prebuild info unpack required F:\Workspace\Electron\Test\test2\node_modules\leveldown\build\Release\leveldown.node successfully
prebuild info install Prebuild successfully installed!
npm verb lifecycle leveldown@1.5.0~install: unsafe-perm in lifecycle true
npm verb lifecycle leveldown@1.5.0~install: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;F:\Workspace\Electron\Test\test2\node_modules\leveldown\node_modules\.bin;F:\Workspace\Electron\Test\test2\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\nodejs\;C:\Program Files\Java\jdk1.8.0_121\bin;C:\Program Files\maven\apache-maven-3.3.9\bin;c:\Python27\;C:\Users\george\AppData\Local\atom\bin;C:\Users\george\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft VS Code\bin
npm verb lifecycle leveldown@1.5.0~install: CWD: F:\Workspace\Electron\Test\test2\node_modules\leveldown
npm info lifecycle abbrev@1.1.0~postinstall: abbrev@1.1.0
npm info lifecycle after@0.8.2~postinstall: after@0.8.2
npm info lifecycle ansi@0.3.1~postinstall: ansi@0.3.1
npm info lifecycle asn1@0.2.3~postinstall: asn1@0.2.3
npm info lifecycle assert-plus@0.2.0~postinstall: assert-plus@0.2.0
npm info lifecycle async@1.5.2~postinstall: async@1.5.2
npm info lifecycle asynckit@0.4.0~postinstall: asynckit@0.4.0
npm info lifecycle aws-sign2@0.6.0~postinstall: aws-sign2@0.6.0
npm info lifecycle aws4@1.6.0~postinstall: aws4@1.6.0
npm info lifecycle balanced-match@1.0.0~postinstall: balanced-match@1.0.0
npm info lifecycle caseless@0.12.0~postinstall: caseless@0.12.0
npm info lifecycle chownr@1.0.1~postinstall: chownr@1.0.1
npm info lifecycle co@4.6.0~postinstall: co@4.6.0
npm info lifecycle concat-map@0.0.1~postinstall: concat-map@0.0.1
npm info lifecycle brace-expansion@1.1.8~postinstall: brace-expansion@1.1.8
npm info lifecycle core-util-is@1.0.2~postinstall: core-util-is@1.0.2
npm info lifecycle assert-plus@1.0.0~postinstall: assert-plus@1.0.0
npm info lifecycle dashdash@1.14.1~postinstall: dashdash@1.14.1
npm info lifecycle deep-extend@0.4.2~postinstall: deep-extend@0.4.2
npm info lifecycle delayed-stream@1.0.0~postinstall: delayed-stream@1.0.0
npm info lifecycle combined-stream@1.0.5~postinstall: combined-stream@1.0.5
npm info lifecycle delegates@1.0.0~postinstall: delegates@1.0.0
npm info lifecycle isarray@0.0.1~postinstall: isarray@0.0.1
npm info lifecycle es6-symbol@3.1.1~postinstall: es6-symbol@3.1.1
npm info lifecycle es6-iterator@2.0.1~postinstall: es6-iterator@2.0.1
npm info lifecycle es5-ext@0.10.30~postinstall: es5-ext@0.10.30
npm info lifecycle d@1.0.0~postinstall: d@1.0.0
npm info lifecycle expand-template@1.1.0~postinstall: expand-template@1.1.0
npm info lifecycle extend@3.0.1~postinstall: extend@3.0.1
npm info lifecycle extsprintf@1.3.0~postinstall: extsprintf@1.3.0
npm info lifecycle forever-agent@0.6.1~postinstall: forever-agent@0.6.1
npm info lifecycle fs.realpath@1.0.0~postinstall: fs.realpath@1.0.0
npm info lifecycle assert-plus@1.0.0~postinstall: assert-plus@1.0.0
npm info lifecycle getpass@0.1.7~postinstall: getpass@0.1.7
npm info lifecycle github-from-package@0.0.0~postinstall: github-from-package@0.0.0
npm info lifecycle graceful-fs@4.1.11~postinstall: graceful-fs@4.1.11
npm info lifecycle har-schema@1.0.5~postinstall: har-schema@1.0.5
npm info lifecycle has-unicode@2.0.1~postinstall: has-unicode@2.0.1
npm info lifecycle hoek@2.16.3~postinstall: hoek@2.16.3
npm info lifecycle boom@2.10.1~postinstall: boom@2.10.1
npm info lifecycle cryptiles@2.0.5~postinstall: cryptiles@2.0.5
npm info lifecycle inherits@2.0.3~postinstall: inherits@2.0.3
npm info lifecycle block-stream@0.0.9~postinstall: block-stream@0.0.9
npm info lifecycle ini@1.3.4~postinstall: ini@1.3.4
npm info lifecycle is-typedarray@1.0.0~postinstall: is-typedarray@1.0.0
npm info lifecycle isarray@1.0.0~postinstall: isarray@1.0.0
npm info lifecycle isexe@2.0.0~postinstall: isexe@2.0.0
npm info lifecycle isstream@0.1.2~postinstall: isstream@0.1.2
npm info lifecycle jsbn@0.1.1~postinstall: jsbn@0.1.1
npm info lifecycle ecc-jsbn@0.1.1~postinstall: ecc-jsbn@0.1.1
npm info lifecycle json-schema@0.2.3~postinstall: json-schema@0.2.3
npm info lifecycle json-stringify-safe@5.0.1~postinstall: json-stringify-safe@5.0.1
npm info lifecycle jsonify@0.0.0~postinstall: jsonify@0.0.0
npm info lifecycle json-stable-stringify@1.0.1~postinstall: json-stable-stringify@1.0.1
npm info lifecycle ajv@4.11.8~postinstall: ajv@4.11.8
npm info lifecycle har-validator@4.2.1~postinstall: har-validator@4.2.1
npm info lifecycle assert-plus@1.0.0~postinstall: assert-plus@1.0.0
npm info lifecycle lodash.pad@4.5.1~postinstall: lodash.pad@4.5.1
npm info lifecycle lodash.padend@4.6.1~postinstall: lodash.padend@4.6.1
npm info lifecycle lodash.padstart@4.6.1~postinstall: lodash.padstart@4.6.1
npm info lifecycle gauge@1.2.7~postinstall: gauge@1.2.7
npm info lifecycle mime-db@1.29.0~postinstall: mime-db@1.29.0
npm info lifecycle mime-types@2.1.16~postinstall: mime-types@2.1.16
npm info lifecycle form-data@2.1.4~postinstall: form-data@2.1.4
npm info lifecycle minimatch@3.0.4~postinstall: minimatch@3.0.4
npm info lifecycle minimist@1.2.0~postinstall: minimist@1.2.0
npm info lifecycle minimist@0.0.8~postinstall: minimist@0.0.8
npm info lifecycle mkdirp@0.5.1~postinstall: mkdirp@0.5.1
npm info lifecycle ms@2.0.0~postinstall: ms@2.0.0
npm info lifecycle debug@2.6.8~postinstall: debug@2.6.8
npm info lifecycle array-index@1.0.0~postinstall: array-index@1.0.0
npm info lifecycle noop-logger@0.1.1~postinstall: noop-logger@0.1.1
npm info lifecycle nopt@3.0.6~postinstall: nopt@3.0.6
npm info lifecycle oauth-sign@0.8.2~postinstall: oauth-sign@0.8.2
npm info lifecycle os-homedir@1.0.2~postinstall: os-homedir@1.0.2
npm info lifecycle os-tmpdir@1.0.2~postinstall: os-tmpdir@1.0.2
npm info lifecycle osenv@0.1.4~postinstall: osenv@0.1.4
npm info lifecycle path-array@1.0.1~postinstall: path-array@1.0.1
npm info lifecycle path-is-absolute@1.0.1~postinstall: path-is-absolute@1.0.1
npm info lifecycle performance-now@0.2.0~postinstall: performance-now@0.2.0
npm info lifecycle process-nextick-args@1.0.7~postinstall: process-nextick-args@1.0.7
npm info lifecycle punycode@1.4.1~postinstall: punycode@1.4.1
npm info lifecycle qs@6.4.0~postinstall: qs@6.4.0
npm info lifecycle safe-buffer@5.1.1~postinstall: safe-buffer@5.1.1
npm info lifecycle semver@5.3.0~postinstall: semver@5.3.0
npm info lifecycle simple-mime@0.1.0~postinstall: simple-mime@0.1.0
npm info lifecycle sntp@1.0.9~postinstall: sntp@1.0.9
npm info lifecycle hawk@3.1.3~postinstall: hawk@3.1.3
npm info lifecycle assert-plus@1.0.0~postinstall: assert-plus@1.0.0
npm info lifecycle string_decoder@0.10.31~postinstall: string_decoder@0.10.31
npm info lifecycle readable-stream@1.1.14~postinstall: readable-stream@1.1.14
npm info lifecycle duplexer2@0.0.2~postinstall: duplexer2@0.0.2
npm info lifecycle stringstream@0.0.5~postinstall: stringstream@0.0.5
npm info lifecycle strip-json-comments@2.0.1~postinstall: strip-json-comments@2.0.1
npm info lifecycle rc@1.2.1~postinstall: rc@1.2.1
npm info lifecycle isarray@0.0.1~postinstall: isarray@0.0.1
npm info lifecycle readable-stream@1.0.34~postinstall: readable-stream@1.0.34
npm info lifecycle tough-cookie@2.3.2~postinstall: tough-cookie@2.3.2
npm info lifecycle tunnel-agent@0.6.0~postinstall: tunnel-agent@0.6.0
npm info lifecycle tweetnacl@0.14.5~postinstall: tweetnacl@0.14.5
npm info lifecycle bcrypt-pbkdf@1.0.1~postinstall: bcrypt-pbkdf@1.0.1
npm info lifecycle sshpk@1.13.1~postinstall: sshpk@1.13.1
npm info lifecycle unzip-response@1.0.2~postinstall: unzip-response@1.0.2
npm info lifecycle url-template@2.0.8~postinstall: url-template@2.0.8
npm info lifecycle util-deprecate@1.0.2~postinstall: util-deprecate@1.0.2
npm info lifecycle readable-stream@2.0.6~postinstall: readable-stream@2.0.6
npm info lifecycle are-we-there-yet@1.1.4~postinstall: are-we-there-yet@1.1.4
npm info lifecycle npmlog@2.0.4~postinstall: npmlog@2.0.4
npm info lifecycle bl@1.0.3~postinstall: bl@1.0.3
npm info lifecycle util-extend@1.0.3~postinstall: util-extend@1.0.3
npm info lifecycle execspawn@1.0.1~postinstall: execspawn@1.0.1
npm info lifecycle uuid@3.1.0~postinstall: uuid@3.1.0
npm info lifecycle assert-plus@1.0.0~postinstall: assert-plus@1.0.0
npm info lifecycle verror@1.10.0~postinstall: verror@1.10.0
npm info lifecycle jsprim@1.4.1~postinstall: jsprim@1.4.1
npm info lifecycle http-signature@1.1.1~postinstall: http-signature@1.1.1
npm info lifecycle request@2.81.0~postinstall: request@2.81.0
npm info lifecycle which@1.3.0~postinstall: which@1.3.0
npm info lifecycle wrappy@1.0.2~postinstall: wrappy@1.0.2
npm info lifecycle once@1.4.0~postinstall: once@1.4.0
npm info lifecycle end-of-stream@1.4.0~postinstall: end-of-stream@1.4.0
npm info lifecycle inflight@1.0.6~postinstall: inflight@1.0.6
npm info lifecycle glob@7.1.2~postinstall: glob@7.1.2
npm info lifecycle rimraf@2.6.1~postinstall: rimraf@2.6.1
npm info lifecycle fstream@1.0.11~postinstall: fstream@1.0.11
npm info lifecycle tar@2.2.1~postinstall: tar@2.2.1
npm info lifecycle node-gyp@3.6.2~postinstall: node-gyp@3.6.2
npm info lifecycle node-ninja@1.0.2~postinstall: node-ninja@1.0.2
npm info lifecycle pump@1.0.2~postinstall: pump@1.0.2
npm info lifecycle xtend@4.0.1~postinstall: xtend@4.0.1
npm info lifecycle simple-get@1.4.3~postinstall: simple-get@1.4.3
npm info lifecycle tar-stream@1.5.4~postinstall: tar-stream@1.5.4
npm info lifecycle tar-fs@1.15.3~postinstall: tar-fs@1.15.3
npm info lifecycle through2@0.6.5~postinstall: through2@0.6.5
npm info lifecycle hyperquest@1.2.0~postinstall: hyperquest@1.2.0
npm info lifecycle jsonist@1.3.0~postinstall: jsonist@1.3.0
npm info lifecycle ghutils@3.2.1~postinstall: ghutils@3.2.1
npm info lifecycle ghrepos@2.0.0~postinstall: ghrepos@2.0.0
npm info lifecycle ghreleases@1.0.6~postinstall: ghreleases@1.0.6
npm info lifecycle abstract-leveldown@2.6.2~postinstall: abstract-leveldown@2.6.2
npm info lifecycle bindings@1.2.1~postinstall: bindings@1.2.1
npm info lifecycle fast-future@1.0.2~postinstall: fast-future@1.0.2
npm info lifecycle nan@2.4.0~postinstall: nan@2.4.0
npm info lifecycle prebuild@4.5.0~postinstall: prebuild@4.5.0
npm info lifecycle leveldown@1.5.0~postinstall: leveldown@1.5.0
npm verb unlock done using C:\Users\george\AppData\Roaming\npm-cache\_locks\staging-cd124d76a49e27f2.lock for F:\Workspace\Electron\Test\test2\node_modules\.staging
F:\Workspace\Electron\Test\test2
`-- leveldown@1.5.0
  +-- abstract-leveldown@2.6.2
  | `-- xtend@4.0.1
  +-- bindings@1.2.1
  +-- fast-future@1.0.2
  +-- nan@2.4.0
  `-- prebuild@4.5.0
    +-- async@1.5.2
    +-- execspawn@1.0.1
    | `-- util-extend@1.0.3
    +-- expand-template@1.1.0
    +-- ghreleases@1.0.6
    | +-- after@0.8.2
    | +-- ghrepos@2.0.0
    | +-- ghutils@3.2.1
    | | `-- jsonist@1.3.0
    | |   `-- hyperquest@1.2.0
    | |     +-- duplexer2@0.0.2
    | |     | `-- readable-stream@1.1.14
    | |     |   `-- isarray@0.0.1
    | |     `-- through2@0.6.5
    | |       `-- readable-stream@1.0.34
    | |         `-- isarray@0.0.1
    | +-- simple-mime@0.1.0
    | `-- url-template@2.0.8
    +-- github-from-package@0.0.0
    +-- minimist@1.2.0
    +-- mkdirp@0.5.1
    | `-- minimist@0.0.8
    +-- node-gyp@3.6.2
    | +-- fstream@1.0.11
    | | `-- inherits@2.0.3
    | +-- glob@7.1.2
    | | +-- fs.realpath@1.0.0
    | | +-- inflight@1.0.6
    | | `-- path-is-absolute@1.0.1
    | +-- graceful-fs@4.1.11
    | +-- minimatch@3.0.4
    | | `-- brace-expansion@1.1.8
    | |   +-- balanced-match@1.0.0
    | |   `-- concat-map@0.0.1
    | +-- nopt@3.0.6
    | | `-- abbrev@1.1.0
    | +-- osenv@0.1.4
    | | `-- os-tmpdir@1.0.2
    | +-- request@2.81.0
    | | +-- aws-sign2@0.6.0
    | | +-- aws4@1.6.0
    | | +-- caseless@0.12.0
    | | +-- combined-stream@1.0.5
    | | | `-- delayed-stream@1.0.0
    | | +-- extend@3.0.1
    | | +-- forever-agent@0.6.1
    | | +-- form-data@2.1.4
    | | | `-- asynckit@0.4.0
    | | +-- har-validator@4.2.1
    | | | +-- ajv@4.11.8
    | | | | +-- co@4.6.0
    | | | | `-- json-stable-stringify@1.0.1
    | | | |   `-- jsonify@0.0.0
    | | | `-- har-schema@1.0.5
    | | +-- hawk@3.1.3
    | | | +-- boom@2.10.1
    | | | +-- cryptiles@2.0.5
    | | | +-- hoek@2.16.3
    | | | `-- sntp@1.0.9
    | | +-- http-signature@1.1.1
    | | | +-- assert-plus@0.2.0
    | | | +-- jsprim@1.4.1
    | | | | +-- assert-plus@1.0.0
    | | | | +-- extsprintf@1.3.0
    | | | | +-- json-schema@0.2.3
    | | | | `-- verror@1.10.0
    | | | |   `-- assert-plus@1.0.0
    | | | `-- sshpk@1.13.1
    | | |   +-- asn1@0.2.3
    | | |   +-- assert-plus@1.0.0
    | | |   +-- bcrypt-pbkdf@1.0.1
    | | |   +-- dashdash@1.14.1
    | | |   | `-- assert-plus@1.0.0
    | | |   +-- ecc-jsbn@0.1.1
    | | |   +-- getpass@0.1.7
    | | |   | `-- assert-plus@1.0.0
    | | |   +-- jsbn@0.1.1
    | | |   `-- tweetnacl@0.14.5
    | | +-- is-typedarray@1.0.0
    | | +-- isstream@0.1.2
    | | +-- json-stringify-safe@5.0.1
    | | +-- mime-types@2.1.16
    | | | `-- mime-db@1.29.0
    | | +-- oauth-sign@0.8.2
    | | +-- performance-now@0.2.0
    | | +-- qs@6.4.0
    | | +-- safe-buffer@5.1.1
    | | +-- stringstream@0.0.5
    | | +-- tough-cookie@2.3.2
    | | | `-- punycode@1.4.1
    | | +-- tunnel-agent@0.6.0
    | | `-- uuid@3.1.0
    | +-- rimraf@2.6.1
    | +-- semver@5.3.0
    | +-- tar@2.2.1
    | | `-- block-stream@0.0.9
    | `-- which@1.3.0
    |   `-- isexe@2.0.0
    +-- node-ninja@1.0.2
    | `-- path-array@1.0.1
    |   `-- array-index@1.0.0
    |     +-- debug@2.6.8
    |     | `-- ms@2.0.0
    |     `-- es6-symbol@3.1.1
    |       +-- d@1.0.0
    |       `-- es5-ext@0.10.30
    |         `-- es6-iterator@2.0.1
    +-- noop-logger@0.1.1
    +-- npmlog@2.0.4
    | +-- ansi@0.3.1
    | +-- are-we-there-yet@1.1.4
    | | `-- delegates@1.0.0
    | `-- gauge@1.2.7
    |   +-- has-unicode@2.0.1
    |   +-- lodash.pad@4.5.1
    |   +-- lodash.padend@4.6.1
    |   `-- lodash.padstart@4.6.1
    +-- os-homedir@1.0.2
    +-- pump@1.0.2
    | +-- end-of-stream@1.4.0
    | `-- once@1.4.0
    |   `-- wrappy@1.0.2
    +-- rc@1.2.1
    | +-- deep-extend@0.4.2
    | +-- ini@1.3.4
    | `-- strip-json-comments@2.0.1
    +-- simple-get@1.4.3
    | `-- unzip-response@1.0.2
    +-- tar-fs@1.15.3
    | `-- chownr@1.0.1
    `-- tar-stream@1.5.4
      +-- bl@1.0.3
      `-- readable-stream@2.0.6
        +-- core-util-is@1.0.2
        +-- isarray@1.0.0
        +-- process-nextick-args@1.0.7
        +-- string_decoder@0.10.31
        `-- util-deprecate@1.0.2

npm WARN enoent ENOENT: no such file or directory, open 'F:\Workspace\Electron\Test\test2\package.json'
npm verb enoent ENOENT: no such file or directory, open 'F:\Workspace\Electron\Test\test2\package.json'
npm verb enoent This is most likely not a problem with npm itself
npm verb enoent and is related to npm not being able to find a file.
npm verb enoent
npm WARN test2 No description
npm verb
npm verb If you need help, you may report this error at:
npm verb     <https://github.com/npm/npm/issues>
npm WARN test2 No repository field.
npm verb
npm verb If you need help, you may report this error at:
npm verb     <https://github.com/npm/npm/issues>
npm WARN test2 No README data
npm verb
npm verb If you need help, you may report this error at:
npm verb     <https://github.com/npm/npm/issues>
npm WARN test2 No license field.
npm verb
npm verb If you need help, you may report this error at:
npm verb     <https://github.com/npm/npm/issues>
npm verb exit [ 0, true ]
npm info ok

**Comment by itsmebhavin** [comment]
@GeorgeWrightz This is not this project related issue so can't say much but we had this issue on one of our machine and we resolve it by installing vs2010.  ( Here is what other developer's comment: I went back and added the C# and C++ pieces in the visual studio 2010 installer and re-ran npm install )

Hope this helps.

**Comment by GeorgeWrightz** [comment]
I understand .. Thanks for your help...
